[features]
seeds = false
[programs.localnet]
solana_twitter = "EMdQpPZ7s3c49wBeqvxpCJBuUwbfSQ47HJefERMmj74E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/test./.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello World!'"
